# Generated by Django 5.0.6 on 2024-06-28 07:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountuser",
            name="account_user_id",
            field=models.UUIDField(
                default=uuid.UUID("b5dfcdd7-068c-4541-9225-a7f12e74f290"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "course_id",
                    models.UUIDField(
                        default=uuid.UUID("e5df7c63-91ab-4ecc-bf67-980531ca6d19"),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("course_name", models.CharField(editable=False, max_length=255)),
                ("course_created_by", models.CharField(max_length=255)),
                ("course_created_date", models.DateTimeField(auto_now_add=True)),
                ("course_updated_by", models.CharField(max_length=255, null=True)),
                ("course_updated_date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("course_id",),
                "indexes": [
                    models.Index(
                        fields=["course_id"], name="account_cou_course__97ad3e_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AttendingCourse",
            fields=[
                (
                    "attending_course_id",
                    models.UUIDField(
                        default=uuid.UUID("7915e6ec-b625-48e9-ae3b-005949f9a85d"),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "attending_account_profile_id",
                    models.CharField(editable=False, max_length=255),
                ),
                ("attending_course_created_by", models.CharField(max_length=255)),
                (
                    "attending_course_created_date",
                    models.DateTimeField(auto_now_add=True),
                ),
                (
                    "attending_course_updated_by",
                    models.CharField(max_length=255, null=True),
                ),
                (
                    "attending_course_updated_date",
                    models.DateTimeField(auto_now_add=True),
                ),
                (
                    "attending_courseid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="account.course"
                    ),
                ),
            ],
            options={
                "ordering": ("attending_course_id",),
                "indexes": [
                    models.Index(
                        fields=["attending_course_id", "attending_courseid"],
                        name="account_att_attendi_ade6c1_idx",
                    )
                ],
            },
        ),
    ]
