# Generated by Django 5.0.6 on 2024-06-30 09:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_alter_accountuser_account_user_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountuser",
            name="account_user_id",
            field=models.UUIDField(
                default=uuid.UUID("694ea6d4-752d-4c2e-8c8c-1d03941449b8"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="attendingcourse",
            name="attending_course_id",
            field=models.UUIDField(
                default=uuid.UUID("52194c93-fdec-4ea8-8dd8-5da52f8154fb"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="course_id",
            field=models.UUIDField(
                default=uuid.UUID("9351dde4-cb71-4b1d-976d-c6e51adffea4"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
