# Generated by Django 5.0.6 on 2024-06-30 09:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0004_alter_accountuser_account_user_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountuser",
            name="account_user_id",
            field=models.UUIDField(
                default=uuid.UUID("ea2a9e88-13a9-4f7a-9390-8b94cc12ca3c"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="attendingcourse",
            name="attending_course_id",
            field=models.UUIDField(
                default=uuid.UUID("a41d62fc-de2f-4b7c-a974-0ef98a0aba1e"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="course_id",
            field=models.UUIDField(
                default=uuid.UUID("2fae8ec5-8f9f-4b40-bca8-d55e3fdc0bda"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
