# Generated by Django 5.0.6 on 2024-07-03 02:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_accountuser_account_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountuser',
            name='account_user_id',
            field=models.UUIDField(default=uuid.UUID('f2118289-5867-48d0-890b-2ebd7e13b43c'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='attendingcourse',
            name='attending_course_id',
            field=models.UUIDField(default=uuid.UUID('5ebaa039-fd87-42be-8ac3-25710bce9115'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.UUIDField(default=uuid.UUID('55e9fc2d-0023-4704-89cd-7472a559b3de'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
