# Generated by Django 5.0.6 on 2024-06-28 07:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_alter_accountuser_account_user_id_course_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountuser",
            name="account_user_id",
            field=models.UUIDField(
                default=uuid.UUID("eeda4a5b-69a4-4110-bb4b-9e75c80f6855"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="attendingcourse",
            name="attending_course_id",
            field=models.UUIDField(
                default=uuid.UUID("9317b05b-b504-4c21-b1bc-96f98ce1fa04"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="course_id",
            field=models.UUIDField(
                default=uuid.UUID("baebe40e-7b9a-46ed-b9ec-38b425d3d8a6"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
