# Generated by Django 5.0.6 on 2024-07-01 03:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0005_alter_accountuser_account_user_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountuser",
            name="account_user_id",
            field=models.UUIDField(
                default=uuid.UUID("7dceddc5-19e0-4fb7-bfc3-5b2eccacbbf4"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="attendingcourse",
            name="attending_course_id",
            field=models.UUIDField(
                default=uuid.UUID("932b6534-9e08-432c-9ddc-f3a9e4dc22bf"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="course_id",
            field=models.UUIDField(
                default=uuid.UUID("5942edb0-a6b4-4024-9d2a-4613bf642d09"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
